### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by JoleneKearse** [The-Arjun-Thakor/Halloween#3]
Hi! I'd like to add a favicon to your site. I think this pumpkin would make it stand out in user's tabs!

![pumpkin](https://user-images.githubusercontent.com/70668540/194062807-7b5451ae-f8dd-4db8-9a53-646afd3f0322.png)
I got it from IconScout and here's the attribution. According to the site's rules attribution isn't required, but I have the link if wanted.
<a href="https://iconscout.com/icons/pumpkin" target="_blank">Pumpkin Icon</a> by <a href="https://iconscout.com/contributors/jemismali">Jemis Mali</a> on <a href="https://iconscout.com">IconScout</a>

**Comment by The-Arjun-Thakor** [comment]
Thanks for this issue and you can share the link it will be helpful for me .
